"""
updater/installer.py — Safe update installation for Windows.

Strategy
--------
* .exe update  → a PowerShell helper script waits for the app to exit,
                 backs up the old binary, copies in the new one, then
                 re-launches the updated app.  (We cannot overwrite a
                 running executable on Windows.)

* .zip / .tar  → extracted into a temp folder, files are merged into
                 the app directory, then the app is restarted normally.

Rollback
--------
The old executable is kept as  <name>.bak  so the user can restore it
manually if anything goes wrong.
"""

import os
import shutil
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path
from typing import Optional

from .utils import get_app_dir, setup_logger

logger = setup_logger()


# ── Archive extraction ───────────────────────────────────────────────────────

def extract_archive(archive_path: str, extract_to: str) -> bool:
    """Extract a .zip or .tar.gz archive.  Returns True on success."""
    archive = Path(archive_path)
    dest    = Path(extract_to)
    try:
        dest.mkdir(parents=True, exist_ok=True)
        name_lower = archive.name.lower()
        if name_lower.endswith(".zip"):
            with zipfile.ZipFile(archive, "r") as zf:
                zf.extractall(dest)
        elif name_lower.endswith((".tar.gz", ".tgz", ".tar.bz2")):
            with tarfile.open(archive) as tf:
                tf.extractall(dest)
        else:
            logger.warning(f"Unknown archive format: {archive.suffix}")
            return False
        logger.info(f"Extracted '{archive.name}' → '{dest}'")
        return True
    except (zipfile.BadZipFile, tarfile.TarError) as exc:
        logger.error(f"Archive extraction failed: {exc}")
        return False
    except OSError as exc:
        logger.error(f"File-system error during extraction: {exc}")
        return False


# ── PowerShell updater script (Windows .exe strategy) ───────────────────────

def _write_ps1_updater(
    old_exe: str,
    new_exe: str,
    pid: int,
    restart: bool,
) -> Optional[str]:
    """
    Write a self-deleting PowerShell script that replaces *old_exe* with
    *new_exe* after *pid* exits, optionally restarting the app.

    Returns the path to the script, or None on failure.
    """
    script_path = Path(old_exe).parent / "_upd_helper.ps1"
    restart_line = f'Start-Process -FilePath "{old_exe}"' if restart else ""

    # Escape backslashes for the PS1 string literals
    old_safe = old_exe.replace("\\", "\\\\")
    new_safe = new_exe.replace("\\", "\\\\")
    script   = script_path.as_posix()

    ps1 = f"""\
# Auto-generated by updater — do not edit
$ErrorActionPreference = 'Stop'

$old = '{old_safe}'
$new = '{new_safe}'
$bak = "$old.bak"

# Wait up to 30 s for the main process to exit
$proc = Get-Process -Id {pid} -ErrorAction SilentlyContinue
if ($proc) {{ $proc.WaitForExit(30000) }}
Start-Sleep -Milliseconds 500

try {{
    if (Test-Path $bak) {{ Remove-Item $bak -Force }}
    if (Test-Path $old)  {{ Copy-Item $old $bak -Force }}
    Copy-Item $new $old -Force
    Remove-Item $new -Force -ErrorAction SilentlyContinue
    Write-Host "Update applied successfully"
}} catch {{
    Write-Host "ERROR: $_"
    exit 1
}}

{restart_line}

# Self-delete
Start-Sleep -Seconds 2
Remove-Item -LiteralPath '{script}' -Force -ErrorAction SilentlyContinue
"""

    try:
        script_path.write_text(ps1, encoding="utf-8")
        logger.info(f"PowerShell updater written: {script_path}")
        return str(script_path)
    except OSError as exc:
        logger.error(f"Could not write updater script: {exc}")
        return None


def apply_exe_update(new_file: str, restart: bool = True) -> bool:
    """
    Schedule an in-place .exe replacement via a PowerShell helper and then
    exit the current process.
    """
    current_exe = sys.executable if getattr(sys, "frozen", False) else \
                  str(Path(sys.argv[0]).resolve())
    pid         = os.getpid()

    script = _write_ps1_updater(current_exe, new_file, pid, restart)
    if not script:
        return False

    try:
        subprocess.Popen(
            ["powershell", "-ExecutionPolicy", "Bypass", "-NonInteractive",
             "-File", script],
            creationflags=subprocess.CREATE_NO_WINDOW,
            close_fds=True,
        )
        logger.info("Updater launched — application will exit")
        return True
    except OSError as exc:
        logger.error(f"Failed to launch PowerShell updater: {exc}")
        return False


# ── Zip / archive update ─────────────────────────────────────────────────────

def apply_zip_update(zip_path: str, restart: bool = True) -> bool:
    """Extract *zip_path* over the application directory, then restart."""
    app_dir   = get_app_dir()
    temp_dir  = app_dir / "_update_temp"

    try:
        if temp_dir.exists():
            shutil.rmtree(temp_dir)
        if not extract_archive(zip_path, str(temp_dir)):
            return False

        for src in temp_dir.rglob("*"):
            if src.is_file():
                rel  = src.relative_to(temp_dir)
                dest = app_dir / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                # Back up existing file
                if dest.exists():
                    dest.rename(dest.with_suffix(dest.suffix + ".bak"))
                shutil.copy2(src, dest)

        shutil.rmtree(temp_dir, ignore_errors=True)
        logger.info("Zip update applied successfully")

        if restart:
            restart_application()
        return True

    except OSError as exc:
        logger.error(f"Zip update failed: {exc}")
        shutil.rmtree(temp_dir, ignore_errors=True)
        return False


# ── Application restart ──────────────────────────────────────────────────────

def restart_application() -> None:
    """Replace the current process with a fresh instance of the application."""
    logger.info("Restarting application…")
    try:
        subprocess.Popen([sys.executable] + sys.argv[1:])
    except OSError as exc:
        logger.error(f"Restart failed: {exc}")
    finally:
        sys.exit(0)


# ── Entry point ──────────────────────────────────────────────────────────────

def install_update(file_path: str, restart: bool = True) -> bool:
    """
    Apply the downloaded update file.

    Chooses the right strategy based on file extension:
      .exe           → PowerShell helper (replace-after-exit)
      .zip / .tar.*  → extract-and-merge into app directory
    """
    path = Path(file_path)
    if not path.exists():
        logger.error(f"Update file not found: {file_path}")
        return False

    ext = path.suffix.lower()
    if ext == ".exe":
        return apply_exe_update(file_path, restart)
    if ext in (".zip", ".gz", ".bz2"):
        return apply_zip_update(file_path, restart)

    # Fallback: assume executable
    logger.warning(f"Unknown extension '{ext}', treating as executable")
    return apply_exe_update(file_path, restart)
